### ISSUE TITLE
Don't notify pe-puppetserver during eyaml installation

### ISSUE THREAD

**Issue by Sharpie** [voxpupuli/puppet-hiera#109]
Notifying `pe-puppetserver` during eyaml installation chains the `hiera::eyaml` class to the `puppet_enterprise` module. This makes it difficult to bootstrap eyaml via `puppet apply` without dragging in the `puppet_enterprise` module and associated classification

**Comment by Sharpie** [comment]
Looks like PR #106 might address this by using a resource collector.

**Comment by dhoppe** [comment]
@Sharpie I think this issue has been solved, since this module does not use `notify` anymore.
