### ISSUE TITLE
eyaml: add puppetlabs/puppetserver_gem as an explicit dependency for PE 2015.3

### ISSUE THREAD

**Issue by cbowlesatx** [voxpupuli/puppet-hiera#113]
FYI,

Was able to get eyaml configuration to work with the correct directories after adding "puppetlabs/puppetserver_gem" to my control repo.  

Might be worth calling that out as an explicit dependency for hiera EYAML configuration.

**Comment by GeoffWilliams** [comment]
I just ran into this.  This should totally be in the documentation and module metadata
