### ISSUE TITLE
Minor: forge doc says 'masterservice', should be 'master_service'

### ISSUE THREAD

**Issue by rjhornsby** [voxpupuli/puppet-hiera#126]
At the bottom of the forge page[1] for the hiera module, it says the parameter name is 'masterservice' but should say 'master_service'.

It's minor, but confusing when Puppet throws an error when trying to use masterservice.

[1] https://forge.puppetlabs.com/hunner/hiera

**Comment by alexjfisher** [comment]
@rjhornsby This was fixed in https://github.com/voxpupuli/puppet-hiera/commit/2ca529e8df7d90a136a9cd719389108e62a610ce and will be included in the soon to be released version 2.1.0. See https://github.com/voxpupuli/puppet-hiera/pull/123

**Comment by alexjfisher** [comment]
Version 2.1.0 is now available under it's new 'puppet' (voxpupuli) namespace. https://forge.puppet.com/puppet/hiera

**Comment by vchepkov** [comment]
Have you decided to change tag format for the releases?
Previous versions didn't have prefix 'v'

i.e. 2.0.1 vs v2.1.0
