### ISSUE TITLE
Invalid package provider puppetserver_gem 

### ISSUE THREAD

**Issue by jvelasquez** [voxpupuli/puppet-hiera#138]
Hi,

I am having the following error, when trying to configure eyaml, I think my version of PE is the issue (PE2016.1.2).

```
Error: Failed to apply catalog: Parameter provider failed on Package[puppetserver hiera-eyaml]: Invalid package provider 'puppetserver_gem' at /etc/puppetlabs/code/environments/production/modules/hiera/manifests/eyaml.pp:66
```

The class declaration is available here: [custom_profile_puppetmaster/manifests/init.pp](https://gist.github.com/jvelasquez/2d3399599cc06d136d5f9e972b1f8021)

**Comment by jyaworski** [comment]
@jvelasquez puppetserver_gem is a separate module that you need.

https://forge.puppet.com/puppetlabs/puppetserver_gem

**Comment by jvelasquez** [comment]
@jyaworski that is true! Thank you very much.
