### ISSUE TITLE
masterservice in the Documentation

### ISSUE THREAD

**Issue by mikalsande** [voxpupuli/puppet-hiera#140]
The documentation states that one has to use add masterservice => 'puppetserver' to the configuration of the hiera module when using the FOSS Puppet verison. In the init.pp this parameter is named master_service.

**Comment by igalic** [comment]
@mikalsande would you like to submit a patch fixing that?

**Comment by kallies** [comment]
This has been fixed in 2ca529e8df7d90a136a9cd719389108e62a610ce already.

**Comment by igalic** [comment]
thank you @kallies (and thanks @tuxmea :)
