### ISSUE TITLE
Variables in a single-quote is changed to value - should not be (according to the README)

### ISSUE THREAD

**Issue by khdevel** [voxpupuli/puppet-hiera#141]
### Affected Puppet, Ruby, OS and module versions/distributions

Puppet v3.8.4
### What are you seeing

In the _/etc/puppet/hiera.yaml_ the values in a _hierarchy_ are completed strings but should be with some variables. According to the README it should work in other way.
### What behavior did you expect instead

After the puppet executes the code my _hiera.yaml_ file looks as below:

```
:hierarchy:
  - hieradata/host_type/dev/foreman
```

But should...:

```
:hierarchy:
  - "hieradata/host_type/%{::deployment_group}/%{::host_type}"
```

If I "escape" the special characters I have a mess in my hiera.yaml:
Configuration:

```
classes:
  - hiera
hiera::hierarchy:
  - 'hieradata/host_type/\%\{\:\:deployment_group\}/\%\{\:\:host_type\}'
```

Output:

```
:hierarchy:
  - 'hieradata/host_type/\x5c%\x5c{\x5c:\x5c:deployment_group\x5c}/\x5c%\x5c{\x5c:\x5c:host_type\}'
```
### How did this behavior get triggered

My configuration for THIS host in hieradata is:

```
classes:
  - hiera
hiera::hierarchy:
  - 'hieradata/host_type/%{::deployment_group}/%{::host_type}'
```

**Comment by ortegaga** [comment]
Well, in fact README doesn't explain the way to "feed" class parameters via hiera itself. Acording to [this](https://tickets.puppetlabs.com/browse/HI-127) ticket, you must define your hierachy this way:
```
hiera::hierarchy:
  - 'hieradata/host_type/%%{}{::deployment_group}/%%{}{::host_type}'
```
At least, this solved the problem for me.

**Comment by khdevel** [comment]
Thank you very much **ortegaga**, finally someone read my issue :) I will check it today!

**Comment by dhoppe** [comment]
@khdevel I assume your tests were successful.
