### ISSUE TITLE
json backend datadir can not be set

### ISSUE THREAD

**Issue by DrOwl** [voxpupuli/puppet-hiera#152]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 2016.2
- Ruby: 2.1.9p490
- Distribution: Debian
- Module version: 2.1.3-rc0
### How to reproduce (e.g Puppet code you use)

class { 'hiera': backends => [yaml , json], datadir => '/path/to/hieradata' }
### What are you seeing

datadir only gets set for :yaml:

---

:backends:
- yaml
- json

:yaml:
   :datadir: /path/to/hieradata
## datadir is customizable for json

:backends:
- yaml
- json

:yaml:
   :datadir: /path/to/hieradata

:json: 
   :datadir: /path/to/hieradata

---

:backends:
- yaml
- json

:yaml:
   :datadir: /path/to/hieradata

:json: 
   :datadir: /path/to/hieradata_json
### Any additional information you'd like to impart

In addition to this :yaml: will allways be set even if its not chosen as a backend

**Comment by DrOwl** [comment]
I have created https://github.com/DrOwl/puppet-hiera/tree/better_backend_support 
but am unsure what tests I should be adding, Can you please offer advice on what tests you would like adding.

**Comment by bastelfreak** [comment]
Hi @DrOwl, we just merged https://github.com/voxpupuli/puppet-hiera/pull/154, could you please test if this works for you?

**Comment by logicminds** [comment]
@DrOwl see [README](https://github.com/voxpupuli/puppet-hiera/blob/master/README.md#parameters) for examples  (backend_options)

**Comment by dhoppe** [comment]
@DrOwl As @logicminds already mentioned, please use `backend_options` to provide a specific `datadir` for `yaml` and `json`.
