### ISSUE TITLE
incompatible changes in version 2.2.0

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-hiera#161]
After upgrading module to version 2.2.0 order of the configured backends has changed

version 2.1.2:

```
:backends:
  - eyaml
  - yaml
```

version 2.2.0:

```
:backends:
- yaml
- eyaml
```

Also, notice lack of spaces before the array

Changing order of the backends can lead to unexpected results (as it was in my case)

**Comment by mmckinst** [comment]
I've run in to the same issue. It can be worked around by specifying the order of the backends. 

```
class { 'hiera':
  backends => [ 'eyaml', 'yaml' ],
}
```

**Comment by vchepkov** [comment]
What about missing spaces? Patch doesn't seem to address that

**Comment by mmckinst** [comment]
it will be parsed the same regardless of the spaces

**Comment by vchepkov** [comment]
But it will cause unnecessary server restart as well
