### ISSUE TITLE
Unknown variable: '::pe_server_version'

### ISSUE THREAD

**Issue by jflorian** [voxpupuli/puppet-hiera#171]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent-1.8.0-1.el7.x86_64, puppetserver-2.6.0-1.el7.noarch
- Ruby: ruby-2.0.0.598-25.el7_1.x86_64
- Distribution: CentOS 7
- Module version: v2.3.0

### How to reproduce (e.g Puppet code you use)
```puppet
     class { '::hiera':
         hierarchy  => [
             'nodes/%{::trusted.certname}',
             'virtual_%{::is_virtual}',
             'common',
         ],
     }
```
### What are you seeing

    Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: '::pe_server_version'. at /etc/puppetlabs/code/environments/production/forge_modules/hiera/manifests/params.pp:39:10 on node ...

### What behaviour did you expect instead

To use it as is?

### Any additional information you'd like to impart

I strongly suspect this is because I have `strict_variables = true` in my
puppet.conf though I've not studied this code that deeply yet.

**Comment by jflorian** [comment]
Based on https://blog.yo61.com/test-for-undefined-fact-in-puppet-with-strict_variables/ I was able to replace each `$::pe_server_version` with `$facts['::pe_server_version']` as a workaround.  I guess the question is, will this work for other supported platforms though?

**Comment by vStone** [comment]
if defined('$::pe_server_version') should also work

**Comment by igalic** [comment]
`$facts[pe_server_version]` is probably the best option, since it transparently abstracts the `defined()` part for us

**Comment by antaflos** [comment]
One of the two occurrences of `$::pe_server_version` is within the body of an `if versioncmp($::puppetversion, '4.0.0') >= 0 { ... }` so `$facts['pe_server_version']` should be safe to use there.

But the other occurrence is not, so using `defined('$::pe_server_version')` is probably the way to go there.

**Comment by jflorian** [comment]
Has this made it a release yet?  I see #175 looks like it was released, but I'm not certain if that resolves this issue or not.  With v2.4.0 I'm still getting `Unknown variable: '::pe_server_version'`

**Comment by ekohl** [comment]
Closing since there has been a release since.
