### ISSUE TITLE
yaml backend is populated when using eyaml

### ISSUE THREAD

**Issue by adamcstephens** [voxpupuli/puppet-hiera#177]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any? We've used this on 3.8->4.3
- Ruby: Any?
- Distribution: Any? We're using RHEL7
- Module version: v1.3.2 (old I know, [but this still is in v2.3.0](https://github.com/voxpupuli/puppet-hiera/blob/master/manifests/init.pp#L151))

## How to reproduce (e.g Puppet code you use)

Set `$::hiera::eyaml` to `true`.

## What are you seeing

Both eyaml and yaml backends are enabled.

## What behaviour did you expect instead

Only the eyaml backend is enabled. It can handle the yaml component.

## Output log

n/a

## Any additional information you'd like to impart

I discovered the impact of this recently from the [troubleshooting hiera blog post](https://puppet.com/blog/troubleshooting-hiera)

> Note: Yaml can contain regular content alongside encrypted content, and the eyaml backend is capable of processing both. This could mean that Puppet is doing the extra work of two passes for no benefit (assuming you are using the same datadir and file extension). If that is the case, removing yaml as a backend in hiera.yaml is advised.

We explicitly changed this in our profile, and saw real world changes. Our hiera can be messy at times, and certain host groups have many nested lookups which cause long catalog compilations. Changing eyaml+yaml to just eyaml dropped catalog compilation times in almost half from ~500 seconds to ~250 seconds.

**Comment by dhoppe** [comment]
I think it is not that easy to remove `yaml` from the `backends`, because the variable `requested_backends` is also used for configuration of the `data_dir`. This could be a problem, if someone uses a different `datadir` for `yaml` and `eyaml`.

**Comment by rnelson0** [comment]
I think this could also be an issue if someone uses `.eyaml` files that are separate from the yaml backend files. Is there a way to disable the yaml backend when desired? That seems like the logical setup, and maybe tweak the docs to show how to use that.
