### ISSUE TITLE
Feature Request: Add Param For Passing Gem Install Options

### ISSUE THREAD

**Issue by seanmalloy** [voxpupuli/puppet-hiera#187]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.6.3
- Ruby: 2.1.9p490
- Distribution: RHEL 7
- Module version: 2.4.0

## What are you seeing
There is not a parameter to pass gem install options. I need to be able to use a proxy to install
the hiera-eyaml gem.

## What behaviour did you expect instead
An option would exist to pass gem install options when installing the hiera-eyaml gem.

## Output log
n/a

## Any additional information you'd like to impart
I am willing to implement this new feature.

**Comment by alexjfisher** [comment]
@seanmalloy I ran into the same problem and have submitted a PR https://github.com/voxpupuli/puppet-hiera/pull/193

Works for me.  Let us know if you have any issues.
