### ISSUE TITLE
Release new tag incorporating #197, #200

### ISSUE THREAD

**Issue by reidmv** [voxpupuli/puppet-hiera#202]
We just got bugfixes in for #197 and #200, fixing a broken fail() function and the ability to use custom Hiera 5 backends, respectively. Can we get a new tag and release to make these fixes available? Thanks!!!

**Comment by mhudson1** [comment]
Is there any way to prioritize creating this tag?  We would like to incorporate these changes into our code but our policies require that we use a tag and not a branch.  I could create a tag on our local copy of this module but would prefer not to clutter our local copy unless creating this tag on the public module is an issue.

**Comment by mhudson1** [comment]
Just wanted to check on this, is there any way we can get this tag created soon or should we just tag internally?

**Comment by reidmv** [comment]
Released v3.1.0
