### ISSUE TITLE
Fails to install with latest puppetlabs/inifile

### ISSUE THREAD

**Issue by iainhallam** [voxpupuli/puppet-hiera#214]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Ruby: 
- Distribution: CentOS 7.4
- Module version: 3.3.1

## How to reproduce
puppet module install puppet-r10k
puppet module install puppet-hiera

## What are you seeing
R10k installs puppetlabs-inifile version 2.2.0, but puppet-hiera specifies < 2.0.0 as its dependency, so then fails to install because it can't satisfy that dependency.

## What behaviour did you expect instead
puppet-hiera working with puppetlabs-inifile >= 2.0.0

## Any additional information you'd like to impart
The major change between puppetlabs-inifile < 2 and >= 2 seems to be the loss of support for Puppet 3; as this is no longer supported, it might be worth upping the dependency in puppet-hiera.

**Comment by ekohl** [comment]
Fixed by now.
