### ISSUE TITLE
update metadata.json dependency for puppetlabs/inifile

### ISSUE THREAD

**Issue by djconn-ncsu** [voxpupuli/puppet-hiera#224]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: n/a
- Ruby: n/a
- Distribution: n/a
- Module version: 3.3.2

## How to reproduce (e.g Puppet code you use)

$ puppet module list --tree
...
Warning: Module 'puppetlabs-inifile' (v2.2.2) fails to meet some dependencies:
  'puppet-hiera' (v3.3.2) requires 'puppetlabs-inifile' (>= 1.4.1 < 2.0.0)
...

## What behaviour did you expect instead
Please allow us to use a newer version of puppetlabs-inifile (current is 2.2.2) without any warnings being generated

**Comment by djconn-ncsu** [comment]
Obviously, I don't know if there *is* a hard dependency requiring a version below 2.0.  I'm just hoping this is a minor oversight :)

**Comment by ekohl** [comment]
61963876d251da4d1cd366d8fd0b306498418b8f allows inifile version 4.x to be used and was released in version 4.0.0.
