### ISSUE TITLE
Incompatible with Puppet-6

### ISSUE THREAD

**Issue by pillarsdotnet** [voxpupuli/puppet-hiera#263]
Puppet-6 includes native support for `hiera-eyaml`.

When I ran this module against a freshly-provisioned puppetserver version 6.3, it *removed* the `hiera-eyaml` gem. (!!!)

**Comment by TJM** [comment]
I suppose that it is either `present` or `absent` there is no "just leave it the heck alone" option :)

**Comment by pillarsdotnet** [comment]
Not that I could find.  Stared at the code for fifteen minutes and gave up.

**Comment by alexjfisher** [comment]
I don't think this is strictly true. I still use it with puppet 6.
```puppet
class profile::hiera
{
  class { 'hiera':
    hiera_version      => '5',
    datadir_manage     => false,
    puppet_conf_manage => false,
    eyaml              => true,
    eyaml_gpg          => true,
    eyaml_extension    => 'yaml',
    create_keys        => false,
    provider           => 'puppetserver_gem',
    manage_package     => true,
    eyaml_gpg_version  => '0.7.3',
  }
}
```
The module did more for me in the past, but I still find a use for it now.

**Comment by alexjfisher** [comment]
@pillarsdotnet Could you share more details? How you're declaring the class, which OS, which puppet packages etc?  I'm interested to see how we can make the default experience better.

**Comment by pillarsdotnet** [comment]
@alexjfisher 

My apologies; I withdraw the accusation.  After completely removing the `puppet-hiera` module, I'm still experiencing the same problem.  The `hiera-eyaml`  puppetserver_gem is present before the first puppet run, and absent afterwards.  I've got a complete `git diff` of `/etc/puppetlabs` and `/opt/puppetlabs` and can't spot where it got removed.  Very frustrating!
