### ISSUE TITLE
Forge Module not Published

### ISSUE THREAD

**Issue by sk-securian** [voxpupuli/puppet-hiera#330]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8

## What are you seeing
Current published forge module for this is version 5.0.1, which was released in 2022... It seems like this is still an active project/contributions were made to allow it to support Puppet 8, so wondering if a new release will be created?

## What behaviour did you expect instead
Forge release that supports Puppet 8 (and newer versions of stdlib and inifile).

**Comment by Dan33l** [comment]
@sk-securian  on the way #334
